### ISSUE TITLE
Utilize commit linting before PR merge.

### ISSUE THREAD

**Issue by jeff-mccoy** [defenseunicorns/uds-core#18]
Introduce a commit-lint enforcement prior to PR merge to keep our commit history/clean + consistent and prepare for our release strategy.

See https://github.com/defenseunicorns/kubernetes-fluent-client/blob/main/.github/workflows/commitlint.yml for an example. This should only enforce the PR title, used for squash commit message.

**Comment by zachariahmiller** [comment]
resolved by https://github.com/defenseunicorns/uds-core/pull/19
