### ISSUE TITLE
k3d cluster not removed on `uds remove k3d-core-demo...`

### ISSUE THREAD

**Issue by andrewg-xyz** [defenseunicorns/uds-core#184]
### Environment
Device and OS: m2 max, 14.2.1
App version: 0.9.0 (uds cli)
Kubernetes distro being used: k3d
Other: 

### Steps to reproduce
1. `uds deploy k3d-core-demo:0.12.0`
2. `uds remove k3d-core-demo:0.12.0 --confirm`

### Expected result

everything deployed gets removed.

### Actual Result

k3d cluster persists until `k3d clsuter delete...`

### Severity/Priority

low

**Comment by mjnagel** [comment]
I think this issue is identical to https://github.com/defenseunicorns/uds-k3d/issues/40 - basically the problem/behavior lives in uds-k3d not having an `onRemove` action. Happy to have that conversation there - think we can close this one out and assume it will be solved in that dependency?

**Comment by andrewg-xyz** [comment]
Agreed! apologies for the fluff

**Comment by mjnagel** [comment]
I actually am rethinking - might make sense to have a basic task in uds-core to destroy the cluster. See my comment https://github.com/defenseunicorns/uds-k3d/issues/40#issuecomment-1949239136 - I feel less good about doing it in the uds-k3d layer vs just as a task to destroy in uds-core/other repos that might consume it.
