### ISSUE TITLE
Possible display name bug in Keycloak

### ISSUE THREAD

**Issue by Michael-Kruggel** [defenseunicorns/uds-core#220]
### Environment
Device and OS: Linux
App version: 0.14.1
Kubernetes distro being used: k3d
Other:

### Steps to reproduce
1. After deploying keycloak, create a new user
2. Login as that user
3. Top right of window where it should display the user's name, it displays "Full Name" instead

### Expected result
  - It should display the full name of the user

### Actual Result
  - It displays what looks like a placeholder value

### Visual Proof (screenshots, videos, text, etc)
![image](https://github.com/defenseunicorns/uds-core/assets/108417058/34240610-9007-4240-ac16-107242e16c23)

### Severity/Priority
  - Visual/Low

**Comment by mjnagel** [comment]
Thanks for opening @Michael-Kruggel - we were tracking but didn't have an issue. Should be resolved by https://github.com/defenseunicorns/uds-identity-config/pull/19 once merged, released, and pulled in here. Will leave this open until that is pulled in.
