### ISSUE TITLE
Update core-istio-dev to optionally deploy keycloak

### ISSUE THREAD

**Issue by zachariahmiller** [defenseunicorns/uds-core#251]
### Is your feature request related to a problem? Please describe.
A common need for testing packages that depend on uds core is to be able to test the integration points with uds-core. While there are several, one of the biggest places is integration with keycloak. All SWF packages will need this for example and there is a desire to do this in a way that is able to run locally and on lower resourced runners for efficiency and cost. This feature request is to modify the internal core-istio package to have an optional keycloak component and to update the core-istio-dev bundle to reimport the package so that the istio pieces and the keycloak pieces are able to be selected via the uds-cli's --packages flag. This will enable developers to be able to select just istio or istio and keycloak as their deployment baseline for the bundles. 

This solution was discussed as a least gross, lowest maintenance way to implement this ability for developers without significant features being added to uds-cli that don't exist today. It is obvious that this could be a slippery slope to add other packages to test integration, but for now this is a a pretty important piece. As the need arises this similar pattern _could_ be used for other packages like Prometheus, but maybe its reasonable for that integration testing to happen in larger tests. That need can be evaluated on a case-by-case basis in the future and handled according to this pattern, objected to or may drive a discussion about adding a capability in uds-cli to better facilitate this process (like component deselection in a package) when that team has more capacity.

This wont be a breaking change for consumers of the core-istio package, but may require slight modifications to their use to remove keycloak if it causes resource issue on their test platform. We will mitigate this by accounting for this functionality in the uds-common tasks and prescribing their use when possible. 

### Describe alternatives you've considered

- many other permutations of this basic idea, however most of those involved producing an additional release artifact which is gross.
- making uds-core have required: false and default: true and implementing a component deselection feature in uds-cli. This is not ideal due to the way we want to force users to always have the right tools deployed and also due to a lack of capacity on the uds-cli teams end while they focus on engine things. 

### Additional context

Discussed with most of the uds-core team to weigh pros and cons. Barring any implementation issues. Came to an agreement with @mjnagel on this path to move forward.

**Comment by zachariahmiller** [comment]
assigned myself and will try to get a PR in for this ASAP 🦄

**Comment by oates** [comment]
Blocked pending conversation between @Racer159 and @jeff-mccoy

**Comment by mjnagel** [comment]
@rjferguson21 did some exploration of enabling this with CLI changes. It seems like we could make some minimal changes to enable deploy time optional components. I think this would be a far cleaner solution and makes sense to do when we own the whole stack (CLI code + uds-core). Might be good to see if @UncleGedd and crew are open to this approach or can think of a different way to handle.

**Comment by zachariahmiller** [comment]
Still kind of unclear on above comment since i had a similar conversation with @rjferguson21 a day or two ago and he backtracked on saying it would be possible with minimal changes, curious as to what changed since that chat. 

Regardless... chatted with @mjnagel after the above comment, per a discussion with @Racer159 and @jeff-mccoy immediate path forward was to implement a change to make a "slim-dev" package instead of "istio-dev", with no optional selection of components. 

I implemented the changes last night in my PR branch and i think its all covered aside from hitting the unrelated, intermittent ci failures (ulimit issue?) in uds-core right now. That is once again ready for review. Holding off on updating the PR description again until folks agree they are good with it. 😆
