### ISSUE TITLE
UDS Core Quickstart Guide

### ISSUE THREAD

**Issue by Jessy-Morris** [defenseunicorns/uds-core#274]
Need a quickstart guide for UDS Core that deploys a 'mission application' and allows users to see metrics. Need an app that can show monitoring/integration with Core. End goal is to have something valuable that users can see when deploying UDS Core. 

Something simple and fun. Either in open source or we create ourselves.

For example: 
- Deploy UDS Core
- Zarf package create off some open source repo
- Zarf package deploy into cluster with UDS Core
- Pull up something to show mission app integration was auto-magic (grafana dash board, neuvector, etc.)

**Comment by Madeline-UX** [comment]
Things to consider when picking an application:
- who is this quickstart for?
- What are the desired outcomes for the user driving this goal of a quick start?
- What do they expect to learn from using this quick start? (@Jessy-Morris began to answer this above)
- What steps would they take after UDS Core quick start (i.e. deploy another bundle? or create their own)
- Are there any anti-patterns this might encourage (ex., users just deploying pre-built bundles?)

**Comment by mjnagel** [comment]
Would like to focus this issue on a revamp to the [existing podinfo tutorial](https://uds.defenseunicorns.com/tutorials/deploy-with-uds-core/). This needs some more definition but initial thoughts on tutorial:
- Make a generic podinfo package and deploy it. Step user through port-forward to access (this could be the existing content), grabbing logs from kubectl, curling metrics? This should probably be marked as an optional step ("the world without UDS").
- Make a podinfo package with a `Package` CR that has:
  - `expose` entry to create virtual service
  - `sso` + `enableAuthserviceSelector` entry to enable SSO
  - `monitor` entry to add metrics scraping?
  - Some of this can likely be borrowed from our [existing test package for podinfo](https://github.com/defenseunicorns/uds-core/blob/main/src/test/zarf.yaml#L27-L42) and the [`Package` CR there](https://github.com/defenseunicorns/uds-core/blob/main/src/test/chart/templates/package.yaml) - potentially want to find a way to share this between tests and docs
- Create a bundle that deploys Core + podinfo zarf package
- Step through accessing podinfo with SSO, hitting some metrics, etc - this should highlight all the things that core provided differently (SSO login, exposed endpoint, metrics accessible in prometheus/grafana, logs searchable in Grafana)

Steps here could be broken into individual docs/steps with takeaways from each.

**Comment by noahpb** [comment]
PR is up here: https://github.com/defenseunicorns/uds-docs-refresh/pull/96

Noting room for future improvement:
- Integrating Package CR into UDS Package via helm chart, perhaps publish an externally facing chart or library chart that users can reference?
- Create additional documents that do a deeper dive and walkthrough on each component of the `Package` CR (ex: logging into Grafana using SSO, observing the auto-generated `NetworkPolicies` block traffic)
