### ISSUE TITLE
Pepr watch endpointslice still isn't working

### ISSUE THREAD

**Issue by corang** [defenseunicorns/uds-core#279]
### Environment
Device and OS: EKS
App version: 0.16.1
Kubernetes distro being used: EKS

### Steps to reproduce
1. Deploy uds core
2. wait for k8s endpointslice to update

### Expected result

netpols are updated with new endpointslice ips

### Actual Result

netpols are never updated

### Visual Proof (screenshots, videos, text, etc)

![image](https://github.com/defenseunicorns/uds-core/assets/1349336/aa019ae9-c83e-4fa8-8131-6e4d26d3cafd)
 All these netpols are from uds-core, notice how a bunch have different ips, if uds-core is functioning correctly these should all be the same

### Severity/Priority

High, cluster functionality keeps breaking when endpointslice updates

### Additional Context
Add any other context or screenshots about the technical debt here.

**Comment by corang** [comment]
Threw together a script to manually cycle all of the packages via the subresource delete patch and they're all the same now

```
#!/bin/bash

PKGS=$(kubectl get pkg -A | awk '{print $1 "," $2}' | tail -n +2)

for PKG in $PKGS
do
  NAMESPACE=$(echo $PKG | cut -d ',' -f 1)
  NAME=$(echo $PKG | cut -d ',' -f 2)
  kubectl patch pkg $NAME -n $NAMESPACE --subresource=status --type=json  -p='[{"op": "remove", "path": "/status"}]'
  sleep 2s
  # wait for status.phase to be Ready
  kubectl wait --for=jsonpath='{.status.phase}'=Ready pkg/$NAME -n $NAMESPACE --timeout=60s
done
```

![image](https://github.com/defenseunicorns/uds-core/assets/1349336/0b888e88-41a9-425d-91de-c3728b60ecc4)

**Comment by cmwylie19** [comment]
Should there be a watch on `When(a.Endpoint)....` then update the CIDR from there? There is a [PR](https://github.com/defenseunicorns/kubernetes-fluent-client/pull/195) in KFC to add `Endpoints` 



```
// Watch for changes to the API server EndpointSlice and update the API server CIDR
When(a.EndpointSlice)
  .IsCreatedOrUpdated()
  .InNamespace("default")
  .WithName("kubernetes")
  .Watch(updateAPIServerCIDRFromEndpointSlice);

// Watch for changes to the API server Service and update the API server CIDR
When(a.Service)
  .IsCreatedOrUpdated()
  .InNamespace("default")
  .WithName("kubernetes")
  .Watch(updateAPIServerCIDRFromService);

```

**Comment by mjnagel** [comment]
Linking https://github.com/defenseunicorns/pepr/issues/745

**Comment by mjnagel** [comment]
Tentatively closing - please reopen or create a new issue if you encounter this problem in latest core versions.
