### ISSUE TITLE
uds deploy k3d-core-istio-dev:0.16.1 fails

### ISSUE THREAD

**Issue by andrewg-xyz** [defenseunicorns/uds-core#283]
Unclear if docs issue or code issue. 

Do I need to build the bundle first?

Should the bundle OCI be published?

Is the bundle named something else?

Is the readme just wrong?

https://github.com/defenseunicorns/uds-core/blob/main/README.md#uds-package-development

**Comment by TristanHoladay** [comment]
looks like it's a release timing issue. The new bundle version named slim-dev hasn't been published yet, but will be with this release https://github.com/defenseunicorns/uds-core/pull/267. 

For now, if you want to use the slim version (istio, pepr, and keycloak) you can build from source with uds tasks

 `uds run -f tasks/create.yaml slim-dev-package --no-progress`
 `uds run -f tasks/create.yaml k3d-slim-dev-bundle --no-progress`
  `uds run -f tasks/deploy.yaml k3d-slim-dev-bundle --no-progress` 

or you can use the istio-dev bundle (istio and pepr). I deployed that a moment ago without any issue.

`uds run k3d-core-istio-dev:0.16.1`

**Comment by mjnagel** [comment]
Hey @andrewg-xyz - thanks for reporting this. Are you having an issue running `uds deploy k3d-core-istio-dev:0.16.1`? That seems to work locally (no errors I can see) so want to confirm that is the exact command you are running.

If you're hitting an issue with the slim-dev one - what @TristanHoladay mentioned above is the explanation for that. Docs on `main` might be ahead of the actual release, so its always good to check the versioned docs (i.e. 0.16.1 - https://github.com/defenseunicorns/uds-core/blob/v0.16.1/README.md#uds-package-development).

**Comment by TristanHoladay** [comment]
@andrewg-xyz the docs and latest release should be synced now. just did `uds deploy k3d-core-slim-dev:0.17.0` without any issues on my nuc. Let us know if you see any issues when you're able to try it out.

**Comment by TristanHoladay** [comment]
@andrewg-xyz i'm going to close this issue for now. please re-open though if you're still having problems with deploying.

**Comment by andrewg-xyz** [comment]
confirmed works for me now :) thanks
