### ISSUE TITLE
UDS Core deployment prerequisites 

### ISSUE THREAD

**Issue by Jessy-Morris** [defenseunicorns/uds-core#294]
- Needing a prerequisite list for deploying UDS Core.
- What does a user who has never deployed UDS Core need in order to successfully deploy? 
- For reference, this is the current prereqs list --> https://uds.defenseunicorns.com/capabilities/uds-deploy/#prerequisites

**Comment by brandtkeller** [comment]
Seeing an error in Promtail with regards to `too many open files` and no prerequisites stating a need to change the `ulimit` on supported hosts.

**Comment by mjnagel** [comment]
Adding another few specifics that came up for cluster pre-config - currently you have to disable the cluster default metrics-server and default loadbalancer in some cases (i.e. rke2 ingress-nginx).

**Comment by RothAndrew** [comment]
UDS Core (specifically, Istio) doesn't work on a fresh ~~Rocky 9~~  RHEL9-based distro due to [this iptables stuff](https://github.com/istio/istio/issues/23009). Solution is to create file `/etc/modules-load.d/istio-iptables.conf` with this content:

```
# These modules need to be loaded on boot so that Istio (as required by
# UDS Core) runs properly.
#
# See also: https://github.com/istio/istio/issues/23009

br_netfilter
nf_nat
xt_REDIRECT
xt_owner
iptable_nat
iptable_mangle
iptable_filter
```

I also had to disable firewalld
```
sudo systemctl stop firewalld
sudo systemctl disable firewalld
```

**Comment by RothAndrew** [comment]
The link in the description is broken. https://uds.defenseunicorns.com/capabilities/uds-deploy/#prerequisites

**Comment by mjnagel** [comment]
Linking relevant docs from istio and distros:
- https://istio.io/latest/docs/ops/deployment/platform-requirements/
- https://docs.k3s.io/installation/requirements#operating-systems
- https://docs.rke2.io/known_issues#firewalld-conflicts-with-default-networking

I'm not sure we can/should necessarily list out all k8s distro pre-reqs that are generic/not specific to uds-core...but we probably should at least provide links for the distros we list on our [support doc](https://uds.defenseunicorns.com/core/deployment/distribution-support/).

**Comment by mjnagel** [comment]
Labelling as a good first issue. Path forward here would be:
- Create a new `prerequisites` document under [this folder](https://github.com/defenseunicorns/uds-core/tree/main/docs/deployment)
- Document necessary host configuration for core. A few starting points:
  - [os-prep script](https://github.com/defenseunicorns/uds-rke2-image-builder/blob/main/packer/scripts/os-prep.sh) for rke2-image-builder has some sysctl changes and kernel modules that can be referenced
  - above mentioned distro specific pieces (disable metrics server/load balancer)
  - reference to any other OS/k8s pre-configuration (maybe link example [RKE2 known issues](https://docs.rke2.io/known_issues)/[requirements doc](https://docs.rke2.io/install/requirements))

We should focus this doc on requirements specific to uds-core (such as the sysctl changes for promtail, modules for istio). Any other k8s distro/os configuration should be linked from the upstream if it is on our support list (EKS, k3d, RKE2).

**Comment by rjferguson21** [comment]
If it's helpful, a similar doc exists already for SWF - https://uds.defenseunicorns.com/mission-capabilities/swf/deploy-swf/#prerequisites

**Comment by lemonprogis** [comment]
Would it be beneficial to have some github gists and link to those?

**Comment by mjnagel** [comment]
@lemonprogis I think we generally lean towards code blocks directly in docs where necessary. Gists would end up being attached to a specific users account (I don't believe org/repo scoped gists are a thing?) and would be out of sync with normal git versioning (while they do track revisions, they wouldn't be attached to a specific commit, tag, etc on the uds-core repo).

Our docs end up on the documentation site [here](https://uds.defenseunicorns.com/), so it's nice to have it all in one page for end user consumption (see [example code block](https://uds.defenseunicorns.com/core/configuration/istio/ingress/#enable-passthrough-gateway)).

**Comment by mjnagel** [comment]
@lemonprogis are you still able to work this ticket? We wanted to prioritize this for the next milestone (~1.5 week out) and are happy to jump on and build on your existing PR if needed.

**Comment by lemonprogis** [comment]
Yep! I'll be picking this up tomorrow now that I've finished some other things.
