### ISSUE TITLE
Neuvector updater pod sidecar never exits

### ISSUE THREAD

**Issue by corang** [defenseunicorns/uds-core#347]
### Steps to reproduce
1. Have neuvector running for any extended period of time

### Expected result
Updater pod sidecars exit along with the main job

### Actual Result
The main container exits and the sidecar runs forever

### Visual Proof (screenshots, videos, text, etc)
Just manually cleared them I can grab a screenshot when it happens again

### Severity/Priority
Low/med I think its mostly visual but I wonder if it affects neuvector's functionality

**Comment by corang** [comment]
As a workaround I've been portforwarding port 15000 from the sidecar and running `curl -X POST http://localhost:15000/quitquitquit` but this is obviously manual and shouldn't be necessary

**Comment by mjnagel** [comment]
This is likely related to the pepr behavior you've seen with watches - [pepr should be doing the sidecar termination](https://github.com/defenseunicorns/uds-core/blob/main/src/pepr/istio/index.ts#L14-L18) (and has successfully in some long running environments from what I've seen).

Good to track this issue, just want to call out that its likely coupled with watch problems - I would check if cycling the pepr watcher picks up those extra pods and terminates them.

**Comment by mjnagel** [comment]
Linking https://github.com/defenseunicorns/pepr/issues/745

**Comment by mjnagel** [comment]
Should be resolved by https://github.com/defenseunicorns/uds-core/pull/419 - leaving open until that is released and we have feedback though.

**Comment by mjnagel** [comment]
Tentatively closing - please reopen or create a new issue if you encounter this problem in latest core versions.
