### ISSUE TITLE
Single capability tests are not failing on error.

### ISSUE THREAD

**Issue by zachariahmiller** [defenseunicorns/uds-core#41]
### Steps to reproduce
1. push a broken deployment
2. watch individual capability tests succeed despite failures and not deploying

### Expected result

uds run task errors and then the github job fails appropriately 

### Actual Result

job succeeds without actually succeeding.

### Visual Proof (screenshots, videos, text, etc)
**https://github.com/defenseunicorns/uds-core/actions/runs/6882758925/job/18721935013?pr=33**

### Severity/Priority

pretty high. Very false sense of security in the pipelines 😆 

### Additional Context
![image](https://github.com/defenseunicorns/uds-core/assets/71521611/2663dcd2-7eae-449b-b747-358b0650b8bd)

**Comment by mjnagel** [comment]
Looks like in multiline `cmd` blocks set -e is not the default behavior. Adding that explicitly fixed it for me locally, but seems like the right default behavior to have?

There might be a good way to implement options to `set` across all tasks in a file too for anything that might need to be overridden. /cc @UncleGedd I think this might have some uds-cli changes required?

**Comment by UncleGedd** [comment]
Can do, maybe we make this the default behavior and have a flag to override. Please feel free to make an issue in UDS CLI if you all would like this implemented

**Comment by mjnagel** [comment]
Opened uds-cli issue - https://github.com/defenseunicorns/uds-cli/issues/204

**Comment by jeff-mccoy** [comment]
#33 fixes the immediate issue in our test until it is fully fixed in UDS/Zarf
