### ISSUE TITLE
Documentation for UDS Core production recommendations

### ISSUE THREAD

**Issue by rjferguson21** [defenseunicorns/uds-core#415]
Currently there exists a [deploy guide](https://uds.defenseunicorns.com/capabilities/uds-deploy/) for running uds-core via our demo bundle which I would say would be our "quickstart", but we need a document that outlines a deploy guide and requirements for a cloud environment.   

### The document at a high level would outline:

* Recommend external dependencies 
   - Certificates for base domain
   - Object Storage (Loki/Velero)
   - PostgreSQL database (Keycloak)
* Walk through a basic example very similar (or identical to what we do for [EKS nightly testing](https://github.com/defenseunicorns/uds-core/blob/05fd407e9c3bf6a0bac33de64e892ce2a63275ac/.github/workflows/test-eks.yaml#L44))

**Comment by mjnagel** [comment]
Related to https://github.com/defenseunicorns/uds-core/issues/387

**Comment by mjnagel** [comment]
Tentatively closing based on these 3 docs covering production configurations
- https://uds.defenseunicorns.com/reference/configuration/resource-configuration-and-ha/
- https://uds.defenseunicorns.com/reference/configuration/ingress/
- https://uds.defenseunicorns.com/reference/uds-core/dns/

We can reopen or scope this differently if we want to cover a tutorial or something different here.
