### ISSUE TITLE
Add a way to add podMonitors under the `monitor` key.

### ISSUE THREAD

**Issue by Racer159** [defenseunicorns/uds-core#417]
### Is your feature request related to a problem? Please describe.

Currently some application charts (like SonarQube's) do not directly expose a way to have a a metrics endpoint behind a service to create a service monitor and instead would need resources created outside of the current chart to facilitate integration with UDS core.  It would be nice if the operator supported podMonitors under the `monitor` key so that these resources were not needed.

### Describe the solution you'd like

- **Given** I have a pod with an exposed metrics endpoint
- **When** I specify a pod monitor in the package CR under `monitor`
- **Then** the operator makes a pod monitor for that pod

### Describe alternatives you've considered
We could create resources outside of the chart that wire things together but it would be simpler to have this feature built in.

### Additional context
https://github.com/defenseunicorns/uds-package-sonarqube/issues/73

**Comment by zachariahmiller** [comment]
Some updates on this. If we want this feature today, given the way Istio mounts the certs into the pods this is going to be nearly impossible to do what we want without it being gross, defeating the [purpose](https://istio.io/v1.1/docs/tasks/security/auth-sds/) of how Istio is mounting the certs or come with caveats. 

It seems like Prometheus will be updating resources only supporting SafeTLSConfig in the future to support file based mounting (see below on that and also context on the issue above), but unsure how long that will take.

References:
https://github.com/prometheus-operator/prometheus-operator/pull/5572
https://github.com/prometheus-operator/prometheus-operator/pull/6113
https://github.com/prometheus-operator/prometheus-operator/issues/4121

As a path forward today it seems like we can either wait for updates to Prometheus or do one of the following options, none of which i love:

- Support pod monitors but with mTLS exception via Istio annotation only when on a dedicated port (so app doesn't have to be exempted from mTLS)
- Make the pepr watch for pods (created or updated and/or on schedule) that are injected and matching the selector of the pod monitor spinning up and read the Istio certs from the mounted volumes and generate a secret that can then be fed into the SafeTLSConfig ref. 
- In lieu of the pod monitor, optionally generate a service 😅 that points to the metrics endpoints of the pods and then generate a ServiceMonitor as it functions currently.

We can also do option 3 per package ad hoc until there are updates to Prometheus that would make this viable with pod monitors and other resources confined to the SafeTLSConfig. Going to sync up with @mjnagel later to discuss the above and see if he has any other, hopefully better, ideas.

Whichever path forward is chosen it likely makes sense to keep this until we can drop in the normal TLSConfig in a later Prometheus version. 

For us (SWF team) in the referenced issue dependency in this ticket, for any of the above approaches we will still need the endpoint authorization bit (that isn't actually referenced in this ticket), so i will probably break that out into another issue and PR. 

@Racer159 FYI

**Comment by mjnagel** [comment]
Following up on discussion mentioned above:
- Viable path forward is probably generating the service + servicemonitor
- May still be a path forward with cert secret creation but needs a bit more exploration to see what is possible - the current servicemonitor spec references a file that is local to the prometheus pod, so _hope_ is that we could likewise reference a secret local to the prometheus namespace (and only need a single secret vs one per podmonitor)

**Comment by zachariahmiller** [comment]
https://github.com/defenseunicorns/pepr/pull/830 In support of this, was merged in on Tuesday. Waiting for a release at which point in time, the included pepr zarf package should be able to have the chart values overridden to add mount the istio certs into the pod to facilitate generating the secret in the prometheus namespace required by the pod monitors

**Comment by zachariahmiller** [comment]
The approach of generating the istio cert secret from pepr for prometheus is seeming more and more problematic and complicated in terms of viability particularly when the cert gets updated. It appears the issues on the Prometheus side referenced in this ticket are now in the operator as experimental...

On latest uds-core i was able to add

```
    additionalConfig: 
      scrapeClasses: 
      - name: istio-certs
        tlsConfig:
          caFile: /etc/prom-certs/root-cert.pem
          certFile: /etc/prom-certs/cert-chain.pem
          keyFile: /etc/prom-certs/key.pem
 ```
  
  and specify a scrape class on Pod Monitor to get the file based tls config in the PodMonitor config. Will be testing again with `insecureSkipVerify: true` and `default: true`, but either way the above approach will greatly reduce the level of complexity involved in getting this working and will facilitate the tls config for resources other than just pod monitors as and added bonus, simplifying the ServiceMonitor implementation as well as many other Prometheus resources that may come up in the future.

**Comment by zachariahmiller** [comment]
Tested the additional options noted in the previous comments and those appeared to work as intended as well!

Final related values snippet for prometheus in uds-core for this is going to be something like:

```
  prometheusSpec:
    additionalConfig: 
      scrapeClasses: 
      - name: istio-certs
        default: true
        tlsConfig:
          caFile: /etc/prom-certs/root-cert.pem
          certFile: /etc/prom-certs/cert-chain.pem
          keyFile: /etc/prom-certs/key.pem
          insecureSkipVerify: true

**Comment by zachariahmiller** [comment]
As such will be refactoring to remove the code related to the secret generation and the updated implementation will include the changes to prometheus values, the podmonitor generation from the package CR, and the support for authorization. Will need to check with @mjnagel on if in light of scrape class functionality we want to modify or remove the service monitor tlsconfig mutation.

**Comment by mjnagel** [comment]
Scrape class definitely seems like the right path forward. I'm unsure on setting a `default` scrape class - while it would work pretty well (and not require any mutations for pod or service monitors) I would want to make sure we have a simple/obvious path for opting out. I haven't dug in too deeply on how `default` works - @zachariahmiller do you know how the opt-out would look? Would someone need another scrape class that does not have the tlsConfig?

I guess path forward:
- Implement scrapeClasses with an istio scrape class by default in prometheus
- Determine if `default` scrape class can easily be opted out of
- If opt-out with default is not "simple", have pepr mutate pod + svc monitors to add the scrape class (using existing skip annotation to opt-out as needed)

**Comment by zachariahmiller** [comment]
Yeah i was going to check i know you have a couple of use cases where you specifically don't want it. I think it will be fairly simple either way. I'm just assuming opting out would be the exception to the rule and as such if it is trivial to work around the default it likely makes the most sense.

**Comment by zachariahmiller** [comment]
Working toward implementing this:

- Default scrape class with istio things + a non-default exempt scrape class
- For someone using the Package CR...

    1. We generate a generic service/pod monitor (no scrape class/tls config things)
    2. We DO NOT provide an ability to opt-out of the scrape class (i.e. no ability to set annotations, scrape class, tlsconfig, etc) - this might be a bit heavy-handed but I think we can make some assumptions based on mTLS being a default when using the Package CR, and they still have options to make their own resources

- For an upstream chart/other ways that monitors are created...

    1. We have a mutation that is only on monitors WithAnnotation of uds/skip-sm-monitor (or whatever the existing annotation is, key point is just filtering on annotation)
    2. This mutation would set scrapeclass to exempt
    3. Someone also has the option of just setting the scrapeclass themselves to exempt
    
    
Additionally, the current mutation behavior will be left to facilitate a deprecation to ease any upgrade issues. 

Finally, the envoy and prometheus pod monitors need to be exempted as do any service or pod monitors pointing at an uninjected namespace (like kubesystem).
