### ISSUE TITLE
Add debug output in CI

### ISSUE THREAD

**Issue by mjnagel** [defenseunicorns/uds-core#42]
### Is your feature request related to a problem? Please describe.

Currently CI could fail on a capability test with little insight into "why". I will see "failed on validate X" or a similar message but don't have any insight into the state of the cluster to see if pods were crashing, pending, etc.

### Describe the solution you'd like

Add an `always()` run step in CI that dumps debug output from the cluster. This could include getting pods, and other applicable resources as needed.

### Describe alternatives you've considered

Local dev would have this feedback but it is nice to have this in CI for quick checks, especially for the individual capability tests.

**Comment by jeff-mccoy** [comment]
Closed in #33
