### ISSUE TITLE
Add documentation about the requirement for egress for OCSP

### ISSUE THREAD

**Issue by rjferguson21** [defenseunicorns/uds-core#459]
[OCSP](https://en.wikipedia.org/wiki/Online_Certificate_Status_Protocol) currently requires egress out on port 80

**Comment by mjnagel** [comment]
@rjferguson21 is there a specific need to document this for the end user or is the [Package CR self-documentation](https://github.com/defenseunicorns/uds-core/blob/main/src/keycloak/chart/templates/uds-package.yaml#L37-L44) of the netpol sufficient here? Unsure if something else was in view - just want to make sure I'm not missing an issue or specific ask around user-facing logs.

**Comment by mjnagel** [comment]
Tentatively closing based on the netpol existing by default and being named to identify it as an OCSP Lookup policy.
