### ISSUE TITLE
Disable loki external analytics reporting

### ISSUE THREAD

**Issue by blancharda** [defenseunicorns/uds-core#487]
### Is your feature request related to a problem? Please describe.
Loki is attempting to phone home.

Glancing at the logs for loki in an environment with limited public egress, we're seeing a lot of these:
```
msg="failed to send usage report" retries=3 err="Post \"https://stats.grafana.org/loki-usage-report\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
```

It seems that our default uds-core install is sending (or attempting to send) a usage report back to grafana. 

### Describe the solution you'd like

Ideally we would disable this by default in uds-core.

### Describe alternatives you've considered
Alternatively, we should at least provide clear documentation on how to disable this feature in a downstream bundle.

**Comment by mjnagel** [comment]
Definitely preferable to disable this by default, I believe we have telemetry/analytics disabled for NeuVector currently. We should likely review Grafana and Loki since both may have a similar analytics behavior.

**Comment by blancharda** [comment]
It seems grafana is also attempting to reach out for (different) resources/checks:
```
logger=plugin.signature.key_retriever t=2024-07-10T15:48:42.889345595Z level=error msg="Error downloading plugin manifest keys" error="Get \"https://grafana.net/api/plugins/ci/keys\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
logger=grafana.update.checker t=2024-07-10T15:48:42.895775976Z level=error msg="Update check failed" error="failed to get stable version from grafana.com: Get \"https://grafana.com/api/grafana/versions/stable\": net/http: TLS handshake timeout" duration=10.007474354s
```
