### ISSUE TITLE
Registry1 flavor is currently untested on nightly eks test

### ISSUE THREAD

**Issue by zack-is-cool** [defenseunicorns/uds-core#504]
### Describe what should be investigated or refactored
Ideally, the registry1 flavor would be tested in the nightly eks tests. Bonus points if the eks tests occur in govcloud as this package is currently used in AWS Govcloud on EKS.

####  Nightly eks test
https://github.com/defenseunicorns/uds-core/blob/main/.github/workflows/test-eks.yaml

### Related issues
https://github.com/defenseunicorns/uds-core/issues/213

edit: updated w/ correct info

**Comment by mjnagel** [comment]
Just to clarify - registry1 is tested on all PRs and before release, but only on k3d. The missing part is nightly (EKS) tests of registry1.

**Comment by mjnagel** [comment]
This should be relatively quick to add to our [EKS workflow](https://github.com/defenseunicorns/uds-core/blob/main/.github/workflows/test-eks.yaml). Some pointers for this:
- Add a matrix for flavor (similar to the [existing k3d PR tests](https://github.com/defenseunicorns/uds-core/blob/main/.github/workflows/pull-request-conditionals.yaml#L70))
- Pass the flavor into the [create task](https://github.com/defenseunicorns/uds-core/blob/main/.github/workflows/test-eks.yaml#L52) with `--set` to ensure we create the necessary package (this is used in [the task](https://github.com/defenseunicorns/uds-core/blob/main/tasks/create.yaml#L4-L6) during [package create](https://github.com/defenseunicorns/uds-core/blob/main/tasks/create.yaml#L19))
- Nice to have - also add `unicorn` flavor to the matrix, setup/auth to cgr should be handled for you already so this should be a simple addition
