### ISSUE TITLE
Grafana logout not working in some environments

### ISSUE THREAD

**Issue by mjnagel** [defenseunicorns/uds-core#515]
### Environment
Device and OS: MBP macOS
App version: 0.22.2
Kubernetes distro being used: k3d

### Steps to reproduce
1. Deploy uds-core (without IDP)
2. Login to Grafana
3. Click logout button

### Expected result

I am logged out of Grafana and my session is terminated in Keycloak.

### Actual Result

I see Grafana refresh but remain logged in. Even with an IDP it appears the session is kept around?

**Comment by chance-coleman** [comment]
Using the `signout_redirect_url` value for grafana will specifically point where/how grafana logs out a user. Adding an additional redirect to that url allows for bypassing the keycloak logout confirmation page as well as redirecting to the grafana login page. Of course upon reaching the grafana login page it will redirect to the keycloak login page, but that is expected.

```yaml
signout_redirect_url: https://sso.###ZARF_VAR_DOMAIN###/realms/uds/protocol/openid-connect/logout?post_logout_redirect_uri=https%3A%2F%2Fgrafana.admin.###ZARF_VAR_DOMAIN###%2Flogin%2Fgeneric_oauth
 ```
