### ISSUE TITLE
Configure authservice to use Redis

### ISSUE THREAD

**Issue by rjferguson21** [defenseunicorns/uds-core#518]
The existing authservice chart uses an in memory session store which makes it impossible to deploy in an HA mode.

**Comment by mjnagel** [comment]
May want to use https://github.com/defenseunicorns/uds-package-valkey for CI testing of HA Authservice?

**Comment by rjferguson21** [comment]
Added a draft PR, probably want to wait for https://github.com/defenseunicorns/pepr/pull/981 so connection string can be included as a secret.
