### ISSUE TITLE
UDS Bundles Tutorial Error on `uds create --confirm`

### ISSUE THREAD

**Issue by belkat14** [defenseunicorns/uds-core#583]
### Environment
Device and OS: 2021 MBP with Apple M1 Pro chip, Sonoma 14.5
App version: 
Kubernetes distro being used: k3d
Other:

### Steps to reproduce
1. Follow the tutorial steps here: https://uds.defenseunicorns.com/bundles/tutorials/
2. If using a MBP change "amd" references to "arm" 
3. Get to uds create step

### Expected result
A successful bundle creation

### Actual Result
Error and no bundle (as far as I can tell). Or at least no podinfo package. -- Confirmed that the bundle deploy command can't find a bundle (even when changing amd reference to arm)

### Visual Proof (screenshots, videos, text, etc)
<img width="1026" alt="image" src="https://github.com/user-attachments/assets/48301202-5d63-474b-a2fe-fee682de330c">

### Severity/Priority
Medium/High - I plan to use Quick Starts for workshops and a smooth process there would be great! We did this demo with a Hero last week and it didn't work so I'd love to follow up with him to try again! 

### Additional Context
Add any other context or screenshots about the technical debt here.

**Comment by mjnagel** [comment]
We likely should revisit the tutorial - I think it may be a bit stale and very possible that some of the commands/packages used aren't interacting as expected.

**Comment by mjnagel** [comment]
Resolved by https://github.com/defenseunicorns/uds-docs/pull/31
