### ISSUE TITLE
Click "View Page Source" on our UDS Docs gives you a 404 near the right place

### ISSUE THREAD

**Issue by belkat14** [defenseunicorns/uds-core#584]
### Environment
Device and OS: MBP with Apple M1 Pro Chip, Sonoma 14.5
App version: n/a
Kubernetes distro being used: n/a
Other: Doc site issue

### Steps to reproduce
1. Navigate to uds.defenseunicorns.com
2. Click "View Page Source"

### Expected result
Arrive in GH at the location of the docs

### Actual Result
End up lost in GH

### Visual Proof (screenshots, videos, text, etc)
<img width="1727" alt="image" src="https://github.com/user-attachments/assets/151cc874-1003-4391-ba8e-ccffbc1edf26">

### Severity/Priority
Medium - fixing will improve UX

### Additional Context
Add any other context or screenshots about the technical debt here.

**Comment by mjnagel** [comment]
Closing as I believe we disabled the source link for now, partially due to some complexities with docs being pulled from multiple repositories. Can re-evaluate if we want to add that back in the future.
