### ISSUE TITLE
Test UDS Core on EKS 1.30

### ISSUE THREAD

**Issue by ntwkninja** [defenseunicorns/uds-core#587]
### Is your feature request related to a problem? Please describe.
Delivery environment in currently on 1.29. We'd like to go to 1.30 with some confidence.

### Describe the solution you'd like

- **Given** a the EKS test in this repo
- **When** is ran
- **Then** a more supported version of k8s is utilized

### Additional context
Current EKS testing is on [1.27](https://github.com/defenseunicorns/uds-core/blob/a0773e7607f5589ee5bf60a97ab0325c1ffdde71/tasks/iac.yaml#L29)

**Comment by mjnagel** [comment]
Related to https://github.com/defenseunicorns/uds-core/issues/327
