### ISSUE TITLE
Ability to configure UDS Core to accept TLS 1.2

### ISSUE THREAD

**Issue by RothAndrew** [defenseunicorns/uds-core#599]
Currently UDS Core requires TLS 1.3+. This is frustrating in a variety of situations due to compatibility issues with clients that don't support 1.3 yet.

Requesting that minimum TLS version be configurable in UDS Core such that I can make it accept 1.2 when I am deploying it.

Proposed solution:

- Make minimum TLS version configurable in UDS Core, with allowed values of 1.2 or 1.3
- When 1.2 is EOLed, exact date unknown estimate 2026, remove 1.2 as valid minimum TLS version

FAQ:

- **Why only 1.2 or 1.3 as allowed values?** v1.1 is already EOLed. 1.2 is not EOLed yet.
- **Why is this needed?** Many client devices still don't support 1.3. 1.3 was released 6 years ago in 2018. It took 10+ years for 1.2 to achieve widespread adoption.

**Comment by mjnagel** [comment]
I'm happy with the proposed solution. For anyone interested in picking this up the main changes would be...
- Modify the template to read a value/conditional for [`minProtocolVersion`](https://github.com/defenseunicorns/uds-core/blob/main/src/istio/chart/templates/gateway.yaml#L35) (my suggestion would be a "supportTLSV1_2" boolean, and if/else on that to be 1.2 or 1.3)
- Add a corresponding default value for ^ to the [values file](https://github.com/defenseunicorns/uds-core/blob/main/src/istio/chart/values.yaml), ensuring that it still defaults to 1.3 only

**Comment by RothAndrew** [comment]
@mjnagel can I trouble you guys for some documentation on how to use this at deploy time?

**Comment by mjnagel** [comment]
@RothAndrew was just typing up a quick note on the resulting PR here. We can also add a note to the [istio ingress docs](https://github.com/defenseunicorns/uds-core/blob/main/docs/configuration/istio/ingress.md) which would surface on the docs site.

There is a new boolean value `tls.supportTLSV1_2` that can be set per gateway using uds-cli overrides. This defaults to `false` (technically undefined, but a falsey value in helm), which maintains the previous default of 1.3 support only.
