### ISSUE TITLE
Keycloak groups claim is full path only

### ISSUE THREAD

**Issue by corang** [defenseunicorns/uds-core#603]
the groups mapper using full path breaks most existing apps (confluence, jira) as they expect just straight group names

### Describe the solution you'd like
I'd like the groups claim to either not be full path, or an alternate groups claim provided that isn't full path

**Comment by rjferguson21** [comment]
@corang We are leaning towards adding new client scope and mapper that adds a separate claim called `bare_groups` that would be the non-full-pathed groups. 

Just wanted to make sure that path worked for you.  I think we'd like it to be opt-in in the sense that you'd have to configure the Package resource to add a [defaultClientScopes](https://github.com/defenseunicorns/uds-package-mattermost/blob/289b48fc9318e2b068e2fa9bf3332c1bdf602ada/chart/templates/uds-package.yaml#L13) with whatever our new scope is called (probably `bare-groups`).

We'd like to avoid referencing non-full-path groups wherever possible because they can be ambiguous so having it be a separate claim ensures apps would have to knowningly consume `bare_groups`. 

/cc @bburky I think this is OK based on ^ but is this a risk at all?

**Comment by corang** [comment]
That I think works for us

**Comment by corang** [comment]
The issue is that top level groups have a leading slash

**Comment by bburky** [comment]
A default `bare_groups` claim is actually potentially vulnerable. I don't want duplicate leaf group names to collide. `/a/foo` and `/b/foo` should not ever be considered the same group `foo`. I think there are plausible deployment models where end users might be able to create groups (federate with AFNET AD, users can create groups by creating MS Teams teams), using full path is the safe option.

If we somehow want implement something like "expose `/a/foo` and `/b/bar` only to client `baz` as `["foo", "bar"]`" (not all groups, a custom mapper of selected groups) that should be ok though.

What was the implementation plan @UnicornChance @rjferguson21  ?

**Comment by rjferguson21** [comment]
@bburky The claim would not be on all clients, and would only be attached if the client was created with:
```
apiVersion: uds.dev/v1alpha1
kind: Package
metadata:
  name: foo
  namespace: foo
spec:
  sso:
    - name: Foo Login
      clientId: uds-foo
      redirectUris:
        - "https://{{ .Values.subdomain }}.{{ .Values.domain }}/*"
      defaultClientScopes:
        - "bare-groups"
```

I can appreciate the risk associated with using ambiguous groups but the alternatives seem to me: 
* create a custom mapper specifically for @corang's use case baked into our realm with explicit group mappings
* have @corang create a custom mapper for his use case that he deploys with a custom realm

I am open to the idea of more specific mapper but it would require us owning some business logic for JIRA/Confluence and perhaps risking implementing something that would have to be bound to whatever top level group/groups @corang requests.

@corang What group hierarchy are you expecting to have? Could we adjust the mapper associated with the `bare_groups` to be scoped so perhaps only groups under `/UDS Core/*` were mapped to `bare-groups`?

My preference would be to proceed as it is implemented and document the functionality as "dev/test only".  I think this would allow people to workaround likely other applications that will have similar quirks processing the full pathed groups.

**Comment by bburky** [comment]
@corang I'm also curious how this "full path breaks most existing apps (confluence, jira)". Do the apps simply display a long group path which you think is poor UI? Or does something about the long path with slashes break the tools?

**Comment by corang** [comment]
@bburky sorry I wrote this issue quickly and while distracted, what I meant was this breaks for a specific delivery customer that is migrating from gitlab sso to keycloak sso where they already had a bunch of top level groups defined. In their case they have a bunch of setup in jira/confluence tied to these specific group names without the leading slash, so the easiest fix was to disable the full group path option as they're using top level groups anyway. I'm open to this being mapped to only sub groups under a specific top level group if that's more secure.

**Comment by bburky** [comment]
Ok! Thanks for the context.

We could perhaps consider dropping the leading slash from group paths. That way top level groups appear as the group name exactly. If there are child groups, they would still have a slash (if you have no child groups, there would be no slashes at all). Except for the fact that this is a bit of a breaking change (do we have existing users today?), this could be a good default for everyone?

If it's too much of a breaking change, we could make this configurable. Or expose it as an (optional?) second claim.

This is also safe security-wise. Just a change of is there a leading slash on the group name.

**Comment by chance-coleman** [comment]
@bburky @rjferguson21 @corang I have attached a [second branch](https://github.com/defenseunicorns/uds-identity-config/compare/main...custom-group-mapper) to this issue, i was able to implement a custom protocol mapper that captures the normal `groups` claim and removes the leading slash and add that group to a new claim called `bare-groups`. 

Feels like this implementation is fairly specific to only @corang 's usecase, making it a bit weird to add to baseline of uds-identity-config as opposed to the generalized approach of `no full path` client scope. Thoughts?
