### ISSUE TITLE
Keycloak fails to deploy when `prometheusRule.enabled` = `true`

### ISSUE THREAD

**Issue by noahpb** [defenseunicorns/uds-core#632]
### Environment
Device and OS: OS X/Colima
App version: v0.24.1
Kubernetes distro being used: k3d

### Steps to reproduce
1. Deploy `uds-core` with an override for `keycloak` that specifies `prometheusRule.enabled=true`

### Expected result
`uds-core` deploys Keycloak successfully with a `PrometheusRule` object
### Actual Result
```log
      WARNING  Retrying (1/3) in 5s: unable to complete the helm chart install/upgrade: template:
               keycloak/templates/prometheusrule.yaml:7:24: executing
               "keycloak/templates/prometheusrule.yaml" at <.Release.Namespace>: nil pointer evaluating
               interface {}.Namespace
```               
### Severity/Priority
low

### Additional Context
Should we be introducing additional testing to our packages? This feature is not enabled by default or tested in ci. There may be other features that are disabled by default that are currently escaping validation.

Relates https://github.com/defenseunicorns/uds-common/issues/428

**Comment by mjnagel** [comment]
> Should we be introducing additional testing to our packages? This feature is not enabled by default or tested in ci. There may be other features that are disabled by default that are currently escaping validation.

I think for Keycloak this is an especially valid concern. Other components we pull in are largely upstream, and we do test most of the specifics that we layer in (istio, netpols, etc). For Keycloak, however, we built the custom config image and the chart so we should have more holistic coverage of at least all the templates.

**Comment by mjnagel** [comment]
For this specific issue the namespace ref needs to be de-scoped to outside of the with block (`.Release.Namespace` -> `$.Release.Namespace`). May be other template problems, but that's the immediate failure.

We may want to consider commenting out/dropping this template though unless we see a strong need for it AND add a validation of it in CI or our internal environment.

**Comment by noahpb** [comment]
Started a draft PR [here](https://github.com/defenseunicorns/uds-core/pull/633) to fix the immediate issue. I'm in favor of dropping the template if its irrelevant.
