### ISSUE TITLE
Velero Azure Blob Support

### ISSUE THREAD

**Issue by rwh85** [defenseunicorns/uds-core#643]
### Is your feature request related to a problem? Please describe.
When deploying UDS Core on Azure AKS it would be nice to have Velero support Azure Blob storage

### Describe the solution you'd like

- **Given** UDS Core is deployed on AKS
- **When** Velero backups are taken
- **Then** They are saved to Azure Blob storage

**Comment by mjnagel** [comment]
I think we can definitely evaluate adding direct support similar to what was done in https://github.com/defenseunicorns/uds-core/pull/424. @rwh85 would you be able to clarify the specific ask here? I'm not overly familiar with Azure/Velero but I suspect there's two pieces:
- The specific azure plugin - could add this image by default probably, my only worry is not being able to easily test in our CI process
- Specific azure config - this should be configurable using [bundle overrides](https://uds.defenseunicorns.com/cli/overrides/) I'd expect, but we can also evaluate and document what is necessary here

**Comment by rwh85** [comment]
@mjnagel We are using bundle overrides for Azure specific values, and this seems like it will work. Other things that need evaluated: 

- Azure image needs to ship with Zarf package
- Azure init container needs configured

Once the image is baked into the flavors and the init container is added I think this will work. I'll no more as soon as I can test  in the next day or so. 

I'm happy to attempt a PR for this if it's that straight forward, however i didn't want to just assume this would be support and also wanted to make sure the way I see it being integrated was inline with that of the UDS Core team.

**Comment by mjnagel** [comment]
Awesome yeah - for the init container I think you could also add it via bundle overrides although that's probably not a great experience. I don't see any real issue adding it to the baseline, I _think_ you can add multiple plugins without issue but not 💯% sure. Keep us posted, but I think a PR to core would be great, definitely want to avoid you needing to fork (worth noting that you could also load the image separately in a mini zarf package with just that image as well).

**Comment by rwh85** [comment]
Cool thanks!I haven't seen the mini zarf package concept anywhere yet, but I'll dig into that. The more I think about this change I think it can be as simple as adding the image to the flavors for the plugin and configuring the init container. I'll test it all out and see what works and get a PR in.
