### ISSUE TITLE
Jobs that error don't have the sidecar killed by pepr

### ISSUE THREAD

**Issue by corang** [defenseunicorns/uds-core#687]
### Steps to reproduce
1. Have a job pod that isn't istio aware error via a non-zero exit code on main container

### Expected result
Pepr kills istio sidecar so that the job pod can restart/retry

### Actual Result
Job pod sidecar runs forever so job never retries/eventually completes

### Severity/Priority
Medium, can break automated deployments

**Comment by mjnagel** [comment]
Lines in question - https://github.com/defenseunicorns/uds-core/blob/main/src/pepr/istio/index.ts#L50-L51

**Comment by mjnagel** [comment]
Should validate the intent here and make sure that jobs are able to retry on failure as expected. Likely will need to update the lines in question to not consider the exit code.
