### ISSUE TITLE
Fix bundle documentation spelling issue

### ISSUE THREAD

**Issue by MxNxPx** [defenseunicorns/uds-core#701]
Typo on these pages:

* https://github.com/defenseunicorns/uds-core/blob/c53126f2401604ab26d58a1cc567cb37f7addadf/bundles/k3d-slim-dev/README.md
* https://github.com/defenseunicorns/uds-core/blob/c53126f2401604ab26d58a1cc567cb37f7addadf/bundles/k3d-standard/README.md

```
[K3d](https://k3d.io/) - Containerized K3s Kubernetes Enviroment
```

should be:
```
[K3d](https://k3d.io/) - Containerized K3s Kubernetes Environment
```

**Comment by chance-coleman** [comment]
adding codespell to pre-commit [PR](https://github.com/defenseunicorns/uds-core/pull/703), will use this issue to update any other spelling issues.
