### ISSUE TITLE
Fix velero documentation spelling issue

### ISSUE THREAD

**Issue by MxNxPx** [defenseunicorns/uds-core#702]
Typo on this page:

https://github.com/defenseunicorns/uds-core/blob/c53126f2401604ab26d58a1cc567cb37f7addadf/src/velero/README.md#plugin-compatability

```
Plugin Compatability
```

Should be:

```
Plugin Compatibility
```

**Comment by chance-coleman** [comment]
adding codespell to pre-commit [PR](https://github.com/defenseunicorns/uds-core/pull/703), will use this issue to update any other spelling issues.
