### ISSUE TITLE
Add nightly CI testing on Azure (AKS)

### ISSUE THREAD

**Issue by MxNxPx** [defenseunicorns/uds-core#727]
Related to https://github.com/defenseunicorns/uds-core/issues/213

Currently we do nightly testing on EKS. In order to expand our testing posture we should also test on AKS in Azure. The EKS testing is contained in these locations:

- Workflow: https://github.com/defenseunicorns/uds-core/blob/main/.github/workflows/nightly-testing.yaml
- Nightly bundle: https://github.com/defenseunicorns/uds-core/tree/main/.github/bundles
- Test infra: https://github.com/defenseunicorns/uds-core/tree/main/.github/test-infra/buckets-iac
- IAC task file: https://github.com/defenseunicorns/uds-core/blob/main/tasks/iac.yaml

Definition of done: Nightly test added to spin up AKS and deploy core (all flavors, matrixed) on it. There are multiple pre-reqs for this work including...

- Setup an Azure (Govcloud?) subscription for CI and plumb it up to GitHub
- Reuse and/or template out an AKS OpenTofu (using the internally built example) and tweak for fully automated create/destroy

**Comment by mjnagel** [comment]
Work ongoing to handle organizational setup for Azure account. Existing example of AKS deployment exists but nothing in CI yet.

**Comment by noahpb** [comment]
Validated functionality in a private repo. Working through final steps to get https://github.com/defenseunicorns/uds-core/pull/908 ready for review.

**Comment by noahpb** [comment]
All validations passing, switching to In Review.

**Comment by mjnagel** [comment]
@noahpb good to close?
