### ISSUE TITLE
Document ports, protocols, services for UDS Core

### ISSUE THREAD

**Issue by mjnagel** [defenseunicorns/uds-core#754]
### Is your feature request related to a problem? Please describe.

When deploying to a secure environment I am required to answer NIST controls, including [SA-4(9)](https://csf.tools/reference/nist-sp-800-53/r4/sa/sa-4/sa-4-9/). This requires documentation of ports, protocols, and services in use in my applications - to include UDS Core.

### Describe the solution you'd like

To provide an easier deployment experience and inheritance of controls, we should provide a document with PPS for end users.

### Additional context

See these resources:
- https://github.com/defenseunicorns/UniRAMP/issues/294
- https://public.cyber.mil/connect/ppsm/
- https://www.esd.whs.mil/Portals/54/Documents/DD/issuances/dodi/855101p.pdf

It would also be ideal if this could be automated, to reduce maintenance needs when applications update/change. I am unsure if there are existing tools that would do this.

**Comment by CloudBeard** [comment]
@rjferguson21 hooked me up with the ports/protocols. 

I will need to add this to the OSCAL Component-Definitions per service (lets the data roll up into other OSCAL models) and update the issue in UniRAMP with any additional documentation/Diagram.

- [ ] PPS added to OSCAL
- [x] UniRAMP Issue Updated 
- [ ] Additional Doc/Diagram created

**Comment by CloudBeard** [comment]
OSCAL update to include PPS is partially blocked until this issue is completed. https://github.com/defenseunicorns/uds-core/issues/797 

The OSCAL can be updated upstream in Compliance-Artifacts and moved over with the decompose work.

**Comment by CloudBeard** [comment]
Updated the [UniRAMP repo's issue](https://github.com/orgs/defenseunicorns/projects/79/views/6?filterQuery=-label%3A%22FedRamp+High%22+-label%3A%22IL-5%22+-label%3A%22IL-6%22++SA-4.9&pane=issue&itemId=59224630&issue=defenseunicorns%7CUniRAMP%7C294) with the data.

Leaving issue open to track it being added to the OSCAL too and brought over.

**Comment by CloudBeard** [comment]
Closing this issue as the following issues will include the OSCAL with Ports/Protocols.

- https://github.com/defenseunicorns/uds-core/issues/1080
- https://github.com/defenseunicorns/uds-core/issues/1081
- https://github.com/defenseunicorns/uds-core/issues/1082
- https://github.com/defenseunicorns/uds-core/issues/1083
- https://github.com/defenseunicorns/uds-core/issues/1084
- https://github.com/defenseunicorns/uds-core/issues/1085
- https://github.com/defenseunicorns/uds-core/issues/1086
- https://github.com/defenseunicorns/uds-core/issues/1087
- https://github.com/defenseunicorns/uds-core/issues/1088
- https://github.com/defenseunicorns/uds-core/issues/1089
- https://github.com/defenseunicorns/uds-core/issues/1090
- https://github.com/defenseunicorns/uds-core/issues/1091
