### ISSUE TITLE
Create and publish Monitoring functional layer

### ISSUE THREAD

**Issue by mjnagel** [defenseunicorns/uds-core#829]
Additional context in https://github.com/defenseunicorns/uds-core/issues/736

As accepted in [the ADR](https://github.com/defenseunicorns/uds-core/blob/main/docs/adrs/0002-uds-core-functional-layers.md) we should create and publish a "Monitoring" functional layer. This layer should include Grafana and Prometheus.

Definition of done for this layer:
- New `packages/monitoring` folder with a zarf.yaml named `core-monitoring` importing grafana and prometheus (plus CRDs)
- Readme identifying the contents of the layer as well as any dependency layers (base and identity-authorization in this case)
- Validation task file, importing validations from components
- CI filters modified to test "monitoring" on changes to appropriate files
- CI workflows/tasks modified to add a "layer test" which builds and deploys the specified layer. This should be used on the CI filter in place of the existing single package test for the relevant package(s)
- Publishing workflows/tasks updated to publish the layer, using monolithic versioning (versioned identical to core itself) - this will also require release-please config updates
- Updating pepr/operator code to properly handle reconciliation when monitoring is not present (i.e. skip service/pod monitoring creation). Also ideally create warning events when a Package CR contains monitor configuration if this layer is not deployed (some [initial draft changes](https://github.com/defenseunicorns/uds-core/pull/665/files#diff-b5316f6ab132ae25f900cb362582c788675e57c8642e9de596960ede8eb9efec) were made to partially handle this with watches)

Existing [draft PR](https://github.com/defenseunicorns/uds-core/pull/665/files) may be helpful in the implementation here.

**Comment by mjnagel** [comment]
Noting one pivot based on where we went with the base layer - CRDs are included in the base layer rather than this one. This was primarily done to reduce some of the complexity around timing with pod/svc monitor creation, but may lead to some changes to the original ticket scope:

> Updating pepr/operator code to properly handle reconciliation when monitoring is not present (i.e. skip service/pod monitoring creation). Also ideally create warning events when a Package CR contains monitor configuration if this layer is not deployed (some [initial draft changes](https://github.com/defenseunicorns/uds-core/pull/665/files#diff-b5316f6ab132ae25f900cb362582c788675e57c8642e9de596960ede8eb9efec) were made to partially handle this with watches)

This part may warrant some additional discussion. Since the CRDs are in the base layer, we could unconditionally create monitoring resources, they would just be extra resources in the cluster. I think we have at least 3 options:
1. Do not change operator code at all, create monitoring resources regardless of monitoring layer existence.
2. Wrap monitoring resources in a conditional for monitoring layer, and create a warning event on the Package CR when not present (the original path recommended in this issue).
3. Wrap monitoring resources in a conditional for monitoring layer, and fail reconciliation on the Package CR when not present (aligned with the approach taken for identity-authorization).

I would heavily lean towards option 1 or 2. While failing reconciliation for SSO (a critical configuration) makes sense, failing on a monitoring integration feels a bit more heavy handed. Option one would provide a benefit of having all monitoring integrations ready for when the layer gets deployed while option 2 keeps from creating extra resources. If we did approach with option 2 we would need to ensure we properly re-reconcile any Package CRs that were previously reconciled without monitoring, in case they requested a pod or service monitor. I think option 1 might be the easy path forward for now in light of that.

**Comment by noahpb** [comment]
I agree with the approach in option one, with two callouts.
>Option one would provide a benefit of having all monitoring integrations ready for when the layer gets deployed while option 2 keeps from creating extra resources. 

~~A broader concern that I have (which may be out of scope for this ticket) is the _when_ in the comment referenced above. With resources being deployed in three separate places (CRDs in base, CRs in packages - deployed unconditionally as "extra" resources, and the monitoring stack itself), we need to ensure that _when_ the monitoring layer gets deployed, it is still compatible with the pre-existing CRDs and CRs (i.e. monitoring stack looks for resources at apiVersion `/v2`, but all of the pre-existing resources are `/v1`). Hopefully this is an edge case, but wanted to call this out.~~ Disregard as all layers will be published lockstep at the same version and we will advise consumers to pull layers at lockstep versions (cc @mjnagel).

Another downside to option 1 could be a misleading understanding of what is actually deployed if just the base layer and non-monitoring layers were deployed into an environment. Perhaps we could annotate or label monitoring CRs with a value that indicates the resource is just a placeholder/is not used until the monitoring layer is deployed.

**Comment by mjnagel** [comment]
Discussed synchronously with @noahpb - we plan to press forward with option 1 which means keeping CRDs in the base layer and making no changes to the operator code. In chatting through this we are not aware of any deployments where opting out of monitoring would be desired, with the exception of extremely minimal edge deployments (i.e. just the base layer). Optimizing at this point for a use case that may not be a need isn't worth the investment in my evaluation, but we could revisit this in the future. There are several complexities with that if we wanted to enable a more optimized flow there, primarily figuring out the timing and what our responsibility for warning/failure looks like.
