### ISSUE TITLE
Lint OSCAL GitHub Workflow triggering on changes to itself

### ISSUE THREAD

**Issue by CloudBeard** [defenseunicorns/uds-core#835]
### Environment
Device and OS:
App version:
Kubernetes distro being used:
Other: GitHub CI

Changes to [GitHub Workflow file](https://github.com/defenseunicorns/uds-core/blob/main/.github/workflows/lint-oscal.yaml) itself trigger the lint-oscal workflow due to its filename.

### Steps to reproduce
1. Changes to the ./github/workflows/lint-oscal.yaml
2. Check CI for failed lint-oscal job

### Expected result
Not to trigger CI lint-oscal

### Actual Result
Triggers the workflow and fails 

### Visual Proof (screenshots, videos, text, etc)
![image](https://github.com/user-attachments/assets/8fa87572-1560-44a4-835c-167de98ffe79)

### Severity/Priority
low/low

### Additional Context
Could have the job continue if no file is found or add an ignore based on filename.

**Comment by mjnagel** [comment]
Fixed this in https://github.com/defenseunicorns/uds-core/pull/825/files#diff-c3e52e710ad40085663d839d09f58210700f1a4c0512780ad2cb89d74b54d768R9
