### ISSUE TITLE
Provide an example `uds-bundle.yaml` that uses functional layers

### ISSUE THREAD

**Issue by noahpb** [defenseunicorns/uds-core#868]
With the introduction of functional layers, we should provide an example configuration with best practices for end users to reference. A starting point can be found at `bundles/k3d-slim-dev/uds-bundle.yaml`. A proper example should include:
 - the base layer at a minimum (required for all layers)
 - references to the layers at their published location
 - indicators that all layers should be versioned lockstep with one another
 - example overrides

The example configuration should not demonstrate all variations of which layers can be referenced in a bundle, rather, it should serve as a starting point for consumers looking to use functional layers.

**Comment by jeff-mccoy** [comment]
As long as this ends up only in the docs and not an actual example we publish it's probably fine. Functional layers are intended for internal use and should not typically be used in production environments, unless by exception.
