### ISSUE TITLE
bad link in uds-deploy documentation 

### ISSUE THREAD

**Issue by huberhefe** [defenseunicorns/uds-core#900]
### Environment
Device and OS: x86 Windows
App version: v0.28.0
Kubernetes distro being used: N/A
Other: 

### Steps to reproduce
1. on page: https://github.com/defenseunicorns/uds-core/blob/main/docs/deployment/uds-deploy.md
2. click "bundles" (on line 24 in the .md)

### Expected result

Not 404.

### Actual Result

404

### Visual Proof (screenshots, videos, text, etc)
404
Page not found. Check the URL or try using the search bar.
### Additional Context
Add any other context or screenshots about the technical debt here.
https://github.com/defenseunicorns/uds-core/blob/main/docs/deployment/uds-deploy.md
references: https://uds.defenseunicorns.com/bundles/

**Comment by huberhefe** [comment]
There's also some likely unintended markdown in the same section.

{{% /alert-note %}}

**Comment by huberhefe** [comment]
I bet:
https://uds.defenseunicorns.com/bundles/
should be:
https://uds.defenseunicorns.com/structure/bundles/

**Comment by mjnagel** [comment]
Hey @huberhefe we made some shifts to the docs - I think I've got the fix for that link in https://github.com/defenseunicorns/uds-core/pull/896 (thanks for reporting this!)
