### ISSUE TITLE
UDS Core Architecture Diagram

### ISSUE THREAD

**Issue by mjnagel** [defenseunicorns/uds-core#919]
Currently we have a "marketing" type graphic on our docs website - https://uds.defenseunicorns.com/ - but do not have any architectural diagram with each component and any infrastructure dependencies (database, object storage, etc). 

We should create an architectural diagram (as code) that includes all components of core with their functionality, connections, dependencies, as well as external interfaces/connections (i.e. load balancers).

This diagram should be for the standard core package, not any of the layers.

Semi-related to https://github.com/defenseunicorns/uds-core/issues/403

**Comment by mjnagel** [comment]
We can/should start from the diagram in https://github.com/defenseunicorns/uds-infrastructure/issues/298 and iterate on it based on current tooling and reduce it to just Core.

**Comment by drewhagen** [comment]
If you need any help, let me know.
I'm going to do a lunch and learn on some diagrams as code on Wednesday

https://docs.google.com/spreadsheets/d/1it9y65gQGqZLD2C62Qy2pn9ibGzlthFfmfZHGIiNTZo/edit?gid=0#gid=0
